name: BlackjackPlugin
version: 1.0
author: JonesDev
main: me.jonesdev.blackjackplugin.BlackjackPlugin
description: Minecraft Inventory GUI Based Blackjack Game.

commands:
  blackjack:
    usage: /(command)
    description: Start blackjack game
  